/**
 * SOURCE-OF-TRUTH map: original frontend HTML → native React Native routes.
 * Original product: glowcast-source/frontend (loaded by ap-services-app WebView).
 * Native must match these screens, buttons, and destinations — not a redesign.
 */
export const SOURCE_SCREENS = [
  { html: 'login.html', route: 'Login', area: 'auth', parity: 'core' },
  { html: 'register.html', route: 'Register', area: 'auth', parity: 'core' },
  { html: 'index.html', route: 'Welcome', area: 'auth', parity: 'core' },
  { html: 'video.html', route: 'Video', area: 'home', parity: 'core' },
  { html: 'explore.html', route: 'Explore', area: 'home', parity: 'core' },
  { html: 'square.html', route: 'Square', area: 'feed', parity: 'core' },
  { html: 'rankings.html', route: 'Rankings', area: 'rankings', parity: 'core' },
  { html: 'chat.html', route: 'Chat / ChatThread', area: 'messages', parity: 'core' },
  { html: 'profile-tab.html', route: 'Profile', area: 'profile', parity: 'core' },
  { html: 'creator-profile.html', route: 'CreatorProfile', area: 'profile', parity: 'core' },
  { html: 'discover-creators.html', route: 'DiscoverCreators', area: 'profile', parity: 'core' },
  { html: 'live-room.html', route: 'LiveRoom', area: 'live', parity: 'core' },
  { html: 'party-room.html', route: 'PartyRoom', area: 'live', parity: 'core' },
  { html: 'party.html', route: 'Explore', area: 'live', parity: 'partial' },
  { html: 'coins-recharge.html', route: 'Recharge', area: 'wallet', parity: 'core' },
  { html: 'withdraw.html', route: 'Withdraw', area: 'wallet', parity: 'core' },
  { html: 'points.html', route: 'Points', area: 'wallet', parity: 'core' },
  { html: 'payment.html', route: 'Payment', area: 'wallet', parity: 'core' },
  { html: 'store.html', route: 'Store', area: 'wallet', parity: 'core' },
  { html: 'vip.html', route: 'Vip', area: 'wallet', parity: 'core' },
  { html: 'levels.html', route: 'Levels', area: 'wallet', parity: 'core' },
  { html: 'cp-home.html', route: 'Cp', area: 'cp', parity: 'partial' },
  { html: 'cp-rankings.html', route: 'CpRankings', area: 'cp', parity: 'core' },
  { html: 'cp-tips.html', route: 'Cp', area: 'cp', parity: 'partial' },
  { html: 'cp-rules.html', route: 'Cp', area: 'cp', parity: 'partial' },
  { html: 'cp-full-guide.html', route: 'Cp', area: 'cp', parity: 'partial' },
  { html: 'visitors.html', route: 'Visitors', area: 'profile', parity: 'core' },
  { html: 'supporter.html', route: 'Supporters', area: 'profile', parity: 'core' },
  { html: 'svip.html', route: 'Svip', area: 'vip', parity: 'core' },
  { html: 'svip-settings.html', route: 'SvipSettings', area: 'vip', parity: 'core' },
  { html: 'svip-intro.html', route: 'SvipIntro', area: 'vip', parity: 'core' },
  { html: 'games/index.html', route: 'Games', area: 'games', parity: 'core' },
  { html: 'games/crazy-fruit.html', route: 'GamePlay', area: 'games', parity: 'partial' },
  { html: 'games/greedy.html', route: 'GamePlay', area: 'games', parity: 'partial' },
  { html: 'games/teen-patti.html', route: 'GamePlay', area: 'games', parity: 'partial' },
  { html: 'games/roulette.html', route: 'GamePlay', area: 'games', parity: 'partial' },
  { html: 'games/food-roulette.html', route: 'GamePlay', area: 'games', parity: 'partial' },
  { html: 'games/card-war.html', route: 'GamePlay', area: 'games', parity: 'partial' },
  { html: 'admin-dashboard.html', route: 'AdminDashboard', area: 'admin', parity: 'core' },
  { html: 'admin-user-details.html', route: 'AdminUserDetails', area: 'admin', parity: 'core' },
  { html: 'admin-worker-details.html', route: 'AdminUserDetails', area: 'admin', parity: 'partial' },
  { html: 'admin-services.html', route: 'AdminDashboard', area: 'admin', parity: 'partial' },
  { html: 'coin-seller-center.html', route: 'CoinSeller', area: 'seller', parity: 'core' },
  { html: 'coin-seller-recharge.html', route: 'SellerStock', area: 'seller', parity: 'core' },
  { html: 'agency-center.html', route: 'AgencyCenter', area: 'agency', parity: 'core' },
  { html: 'add-creator.html', route: 'InviteHost', area: 'agency', parity: 'core' },
  { html: 'invite-agency.html', route: 'InviteAgency', area: 'agency', parity: 'core' },
  { html: 'bd-center.html', route: 'BdCenter', area: 'agency', parity: 'core' },
  { html: 'hierarchy.html', route: 'Hierarchy', area: 'agency', parity: 'core' },
  { html: 'host-agency.html', route: 'HostAgency', area: 'agency', parity: 'core' },
  { html: 'host-policies.html', route: 'HostPolicies', area: 'agency', parity: 'core' },
  { html: 'streamer-center.html', route: 'StreamerCenter', area: 'live', parity: 'core' },
  { html: 'live-verify.html', route: 'LiveVerify', area: 'live', parity: 'core' },
  { html: 'live-application.html', route: 'LiveApplication', area: 'live', parity: 'core' },
  { html: 'role-apply.html', route: 'RoleApply', area: 'profile', parity: 'core' },
  { html: 'roles-guide.html', route: 'RoleApply', area: 'profile', parity: 'partial' },
  { html: 'referral.html', route: 'Referral', area: 'profile', parity: 'core' },
  { html: 'invite-agency.html', route: 'Referral', area: 'profile', parity: 'partial' },
  { html: 'notification-settings.html', route: 'NotificationSettings', area: 'settings', parity: 'core' },
  { html: 'help.html', route: 'Help', area: 'settings', parity: 'core' },
  { html: 'privacy.html', route: 'Legal', area: 'settings', parity: 'core' },
  { html: 'privacypolicy.html', route: 'Legal', area: 'settings', parity: 'core' },
  { html: 'terms.html', route: 'Legal', area: 'settings', parity: 'core' },
  { html: 'become-a-pro.html', route: 'BecomePro', area: 'profile', parity: 'core' },
  { html: 'privileges.html', route: 'Privileges', area: 'profile', parity: 'core' },
  { html: 'lucky-gifts.html', route: 'LuckyGifts', area: 'gifts', parity: 'core' },
  { html: 'services.html', route: 'Services', area: 'bookings', parity: 'core' },
  { html: 'service-details.html', route: 'ServiceDetails', area: 'bookings', parity: 'core' },
  { html: 'booking.html', route: 'Services', area: 'bookings', parity: 'partial' },
  { html: 'booking-details.html', route: 'ServiceDetails', area: 'bookings', parity: 'partial' },
  { html: 'customer-dashboard.html', route: 'WorkerDashboard', area: 'bookings', parity: 'partial' },
  { html: 'worker-dashboard.html', route: 'WorkerDashboard', area: 'bookings', parity: 'core' },
  { html: 'worker-profile.html', route: 'CreatorProfile', area: 'profile', parity: 'partial' },
  { html: 'topics.html', route: 'Topics', area: 'feed', parity: 'core' },
  { html: 'topic-watch.html', route: 'Video', area: 'feed', parity: 'partial' },
  { html: 'withdraw-notices.html', route: 'Withdraw', area: 'wallet', parity: 'partial' },
  { html: 'withdraw-details.html', route: 'WalletHistory', area: 'wallet', parity: 'partial' },
  { html: 'dashboard.html', route: 'AdminDashboard', area: 'admin', parity: 'partial' },
  { html: 'add-creator.html', route: 'AdminDashboard', area: 'admin', parity: 'partial' },
];

export const BOTTOM_NAV = [
  { html: 'video.html', native: 'Video', label: 'Video' },
  { html: 'rankings.html', native: 'Rankings', label: 'Rankings' },
  { html: 'explore.html', native: 'Explore', label: 'Explore' },
  { html: 'chat.html', native: 'Chat', label: 'Chat' },
  { html: 'profile-tab.html', native: 'Profile', label: 'Profile' },
];

export const PROFILE_MENU = [
  { label: 'Admin Dashboard', route: 'AdminDashboard', role: 'admin' },
  { label: 'Invite ($14/person)', route: 'Referral' },
  { label: 'Host earning policies', route: 'HostPolicies' },
  { label: 'Apply for Host / Agency / Seller', route: 'RoleApply' },
  { label: 'Coin Seller Center', route: 'CoinSeller', role: 'coin_seller' },
  { label: 'Host / Streamer Center', route: 'StreamerCenter' },
  { label: 'My posts & videos', route: 'MyPosts' },
  { label: 'My Agency / Change Agency', route: 'HostAgency', role: 'host' },
  { label: 'Live verification & selfie', route: 'LiveVerify' },
  { label: 'BD Center', route: 'BdCenter', role: 'bd' },
  { label: 'Hierarchy', route: 'Hierarchy', role: 'bd' },
  { label: 'Agency Center', route: 'AgencyCenter', role: 'agency' },
  { label: 'My Dashboard', route: 'WorkerDashboard', role: 'worker' },
  { label: 'Store', route: 'Store' },
  { label: 'CP House', route: 'Cp' },
  { label: 'CP Rankings', route: 'CpRankings' },
  { label: 'Visitors', route: 'Visitors' },
  { label: 'AP SVIP', route: 'Svip' },
  { label: 'Level', route: 'Levels' },
  { label: 'VIP Privileges', route: 'Vip' },
  { label: 'Rankings', route: 'Rankings' },
  { label: 'Messages', route: 'Chat' },
  { label: 'Become a Pro', route: 'BecomePro' },
  { label: 'Services', route: 'Services' },
  { label: 'My bookings', route: 'MyServiceBookings' },
  { label: 'Services Center', route: 'WorkerDashboard', role: 'worker' },
  { label: 'Lucky gifts', route: 'LuckyGifts' },
  { label: 'Privileges', route: 'Privileges' },
  { label: 'Games', route: 'Games' },
  { label: 'Help', route: 'Help' },
  { label: 'Settings', route: 'Settings' },
];

export const ADMIN_SECTIONS = [
  'overview', 'platform', 'users', 'workers', 'services', 'bookings', 'payments',
  'recharges', 'withdrawals', 'notifications', 'role-applications', 'bd-hierarchy',
  'referrals', 'reviews', 'analytics', 'reports', 'settings',
];
