/** Google Noto Animated Emoji GIFs — looping stickers, same family WhatsApp uses. */
function noto(code) {
  return `https://fonts.gstatic.com/s/e/notoemoji/latest/${code}/512.gif`;
}

function pack(items) {
  return items.map(([id, code, label]) => ({ id, uri: noto(code), label }));
}

export const STICKER_TABS = [
  { id: 'emoji', glyph: '😊', kind: 'emoji' },
  {
    id: 'love',
    glyph: '❤️',
    kind: 'stickers',
    pack: pack([
      ['heart', '2764_fe0f', 'Heart'],
      ['spark', '1f496', 'Sparkle'],
      ['kiss', '1f48b', 'Kiss'],
      ['eyes', '1f60d', 'Love'],
      ['ring', '1f48d', 'Ring'],
      ['rose', '1f339', 'Rose'],
      ['cupid', '1f498', 'Cupid'],
      ['two', '1f495', 'Two hearts'],
      ['revolving', '1f49e', 'Revolving'],
      ['heartbeat', '1f493', 'Heartbeat'],
      ['bouquet', '1f490', 'Bouquet'],
      ['teddy', '1f9f8', 'Teddy'],
    ]),
  },
  {
    id: 'fun',
    glyph: '😂',
    kind: 'stickers',
    pack: pack([
      ['lol', '1f602', 'LOL'],
      ['rofl', '1f923', 'ROFL'],
      ['wink', '1f609', 'Wink'],
      ['cool', '1f60e', 'Cool'],
      ['party', '1f389', 'Party'],
      ['fire', '1f525', 'Fire'],
      ['up', '1f44d', 'Like'],
      ['clap', '1f44f', 'Clap'],
      ['joy', '1f602', 'Joy'],
      ['starstruck', '1f929', 'Star'],
      ['zany', '1f92a', 'Zany'],
      ['partying', '1f973', 'Party face'],
    ]),
  },
  {
    id: 'feel',
    glyph: '🥺',
    kind: 'stickers',
    pack: pack([
      ['please', '1f97a', 'Please'],
      ['cry', '1f62d', 'Cry'],
      ['sad', '1f622', 'Sad'],
      ['hug', '1f917', 'Hug'],
      ['pray', '1f64f', 'Pray'],
      ['sleep', '1f634', 'Sleep'],
      ['think', '1f914', 'Think'],
      ['wow', '1f62e', 'Wow'],
      ['angry', '1f621', 'Angry'],
      ['sick', '1f922', 'Sick'],
      ['hot', '1f975', 'Hot'],
      ['cold', '1f976', 'Cold'],
    ]),
  },
  {
    id: 'gestures',
    glyph: '🙌',
    kind: 'stickers',
    pack: pack([
      ['wave', '1f44b', 'Wave'],
      ['ok', '1f44c', 'OK'],
      ['peace', '270c_fe0f', 'Peace'],
      ['punch', '1f44a', 'Punch'],
      ['muscle', '1f4aa', 'Strong'],
      ['point', '1f449', 'Point'],
      ['fingers', '1f91e', 'Crossed'],
      ['loveu', '1f91f', 'Love you'],
      ['clap2', '1f44f', 'Clap'],
      ['raised', '1f64c', 'Raise'],
      ['palms', '1f932', 'Palms'],
      ['handshake', '1f91d', 'Handshake'],
    ]),
  },
  {
    id: 'pets',
    glyph: '🐻',
    kind: 'stickers',
    pack: pack([
      ['bear', '1f43b', 'Bear'],
      ['panda', '1f43c', 'Panda'],
      ['cat', '1f431', 'Cat'],
      ['dog', '1f436', 'Dog'],
      ['lion', '1f981', 'Lion'],
      ['chick', '1f423', 'Chick'],
      ['bunny', '1f430', 'Bunny'],
      ['frog', '1f438', 'Frog'],
      ['unicorn', '1f984', 'Unicorn'],
      ['monkey', '1f435', 'Monkey'],
      ['fox', '1f98a', 'Fox'],
      ['penguin', '1f427', 'Penguin'],
    ]),
  },
  {
    id: 'food',
    glyph: '🍕',
    kind: 'stickers',
    pack: pack([
      ['pizza', '1f355', 'Pizza'],
      ['burger', '1f354', 'Burger'],
      ['cake', '1f382', 'Cake'],
      ['donut', '1f369', 'Donut'],
      ['icecream', '1f366', 'Ice cream'],
      ['coffee', '2615', 'Coffee'],
      ['tea', '1f375', 'Tea'],
      ['boba', '1f9cb', 'Boba'],
      ['apple', '1f34e', 'Apple'],
      ['ramen', '1f35c', 'Ramen'],
      ['taco', '1f32e', 'Taco'],
      ['popcorn', '1f37f', 'Popcorn'],
    ]),
  },
  {
    id: 'party',
    glyph: '🎉',
    kind: 'stickers',
    pack: pack([
      ['tada', '1f389', 'Tada'],
      ['cake2', '1f382', 'Cake'],
      ['trophy', '1f3c6', 'Trophy'],
      ['star', '2b50', 'Star'],
      ['gift', '1f381', 'Gift'],
      ['crown', '1f451', 'Crown'],
      ['sparkles', '2728', 'Sparkle'],
      ['confetti', '1f38a', 'Confetti'],
      ['balloon', '1f388', 'Balloon'],
      ['medal', '1f3c5', 'Medal'],
      ['mic', '1f3a4', 'Mic'],
      ['disco', '1f57a', 'Dance'],
    ]),
  },
];
