# Project-wide Gradle settings.

# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.

# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
org.gradle.jvmargs=-Xmx1536m

# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true

# AndroidX package structure to make it clearer which packages are bundled with the
# Android operating system, and which are packaged with your app's APK
# https://developer.android.com/topic/libraries/support-library/androidx-rn
android.useAndroidX=true

MYAPP_UPLOAD_STORE_FILE=ap-services-upload.jks
MYAPP_UPLOAD_KEY_ALIAS=5bd7bfebf9984af3f91e61db58316912
MYAPP_UPLOAD_STORE_PASSWORD=c108416c5d1bd07f00af1221c49d50e8
MYAPP_UPLOAD_KEY_PASSWORD=63bc2638fc735b58648ec57bc260edd2
